[project]
name = "baixarvideos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.53.1",
    "yt-dlp>=2026.1.31",
]
