[theme]
base = "light"
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500

[client]
showErrorDetails = true